// <auto-generated />
using ImdbSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImdbSearch.Migrations
{
    [DbContext(typeof(ImdbDbContext))]
    [Migration("20260608102608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ImdbSearch.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("ImdbSearch.Models.Rating", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TConst");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ImdbSearch.Models.Title", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TConst");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("ImdbSearch.Models.TitleGenre", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TConst", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TitleGenres");
                });

            modelBuilder.Entity("ImdbSearch.Models.Rating", b =>
                {
                    b.HasOne("ImdbSearch.Models.Title", "Title")
                        .WithOne("Rating")
                        .HasForeignKey("ImdbSearch.Models.Rating", "TConst")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ImdbSearch.Models.TitleGenre", b =>
                {
                    b.HasOne("ImdbSearch.Models.Genre", "Genre")
                        .WithMany("TitleGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImdbSearch.Models.Title", "Title")
                        .WithMany("TitleGenres")
                        .HasForeignKey("TConst")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ImdbSearch.Models.Genre", b =>
                {
                    b.Navigation("TitleGenres");
                });

            modelBuilder.Entity("ImdbSearch.Models.Title", b =>
                {
                    b.Navigation("Rating");

                    b.Navigation("TitleGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
